version: '3.8'

services:
    dev:
        container_name: compasso-uol-desafio-dev
        image: compasso-uol-desafio-dev
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: yarn start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: compasso-uol-desafio-prod
        image: compasso-uol-desafio-prod
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: yarn start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    nesjs-network:
