version: '3.8'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27018:27017
    prod:
        container_name: compasso-uol-desafio-prod
        image: compasso-uol-desafio-prod
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command:
            [
                './wait-for-it.sh',
                'mongo:27017',
                '-t',
                '10',
                '--',
                'node',
                'dist/main.js',
            ]
        ports:
            - 8080:8080
        depends_on:
            - mongo
        environment:
            NODE_ENV: docker
        restart: unless-stopped
